package network.ike.docs.koncept;

import org.asciidoctor.ast.Document;
import org.asciidoctor.ast.PhraseNode;
import org.asciidoctor.ast.StructuralNode;
import org.asciidoctor.extension.InlineMacroProcessor;
import org.asciidoctor.extension.Name;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.WeakHashMap;
import java.util.concurrent.ConcurrentHashMap;

/**
 * AsciidoctorJ inline macro processor that handles {@code k:ConceptName[]}
 * syntax in AsciiDoc documents.
 * <p>
 * Usage in AsciiDoc:
 * <pre>
 * The patient presented with k:HeartFailure[] and k:AorticStenosis[].
 * A label override: k:HeartFailure[Congestive Heart Failure].
 * </pre>
 * <p>
 * Each reference renders as the concept's Komet identicon — a LifeHash image
 * byte-identical to what Komet draws — linked to the koncept's glossary
 * entry, with the form chosen per backend:
 * <ul>
 *   <li>{@code html5} / CSS-PDF (Prince, AH, WeasyPrint): an inline
 *       {@code <img>} with a base64 {@code data:} URI.</li>
 *   <li>{@code docbook5} &rarr; FO (FOP/XEP): an {@code <inlinemediaobject>}
 *       referencing a generated PNG file.</li>
 *   <li>{@code pdf} (Prawn): a native inline image node referencing the PNG.</li>
 * </ul>
 * When no identicon can be computed — the koncept has no resolvable PublicId,
 * or {@code :koncept-identicon:} is {@code false} — each backend falls back to
 * a text badge. The glossary is auto-generated by {@link KonceptGlossaryProcessor}.
 * <p>
 * All referenced koncepts are collected in a document-scoped registry
 * for deduplication and glossary generation.
 */
@Name("k")
public class KonceptInlineMacro extends InlineMacroProcessor {

    /** Creates a new inline macro processor instance. */
    public KonceptInlineMacro() {
    }

    private static final Logger LOG = LoggerFactory.getLogger(KonceptInlineMacro.class);

    /**
     * Static registry keyed by Document identity. Uses WeakHashMap so entries
     * are garbage-collected when the Document is no longer referenced.
     * AsciidoctorJ 3.0 does not preserve Java objects in document attributes,
     * so a static map is used for inter-extension communication.
     */
    private static final Map<Document, Map<String, KonceptEntry>> REGISTRIES =
            new WeakHashMap<>();

    @Override
    public PhraseNode process(StructuralNode parent, String target, Map<String, Object> attributes) {
        Document doc = parent.getDocument();
        Map<String, KonceptEntry> registry = getOrCreateRegistry(doc);

        // Register this reference (idempotent on first occurrence)
        registry.computeIfAbsent(target, KonceptEntry::new)
                .incrementRefCount();

        LOG.debug("Koncept reference: {} (total refs: {})",
                target, registry.get(target).getRefCount());

        // Determine display label
        // Positional attribute 1 is the content inside brackets: k:Target[label]
        String label = resolveLabel(target, attributes);

        String backend = doc.getAttribute("backend", "html5").toString();
        Optional<String> idString = resolveIdString(doc, target);

        // Prawn PDF: a passthrough <img> is not rendered by the Prawn
        // converter, so return a real inline image node. Fall through to the
        // text badge below when no identicon is available.
        if ("pdf".equals(backend) && idString.isPresent()) {
            return createIdenticonImageNode(parent, target, label, idString.get());
        }

        String rendered;
        if ("docbook5".equals(backend) || "docbook".equals(backend)) {
            rendered = idString.isPresent()
                    ? renderDocbookIdenticon(target, label, idString.get())
                    : renderDocbookBadge(target, label);
        } else if ("pdf".equals(backend)) {
            // Prawn PDF without an identicon: only basic HTML is supported.
            rendered = "<strong><font color=\"#2a5a8a\">K</font></strong>"
                    + "<code>" + escapeXml(label) + "</code>";
        } else {
            // html5 and CSS-based PDF backends (Prince, AH, WeasyPrint).
            rendered = idString.isPresent()
                    ? renderHtmlIdenticon(target, label, idString.get())
                    : KonceptSvgRenderer.render(target, label);
        }

        // Return as inline passthrough (no further substitution)
        return createPhraseNode(parent, "quoted", rendered,
                Map.of("subs", ":none"));
    }

    /**
     * Resolve the koncept's identicon idString, honouring the
     * {@code :koncept-identicon:} toggle (default on). Empty when the toggle
     * is off or the koncept has no resolvable PublicId.
     */
    private Optional<String> resolveIdString(Document doc, String target) {
        Object flag = doc.getAttribute("koncept-identicon", "true");
        if ("false".equalsIgnoreCase(String.valueOf(flag))) {
            return Optional.empty();
        }
        return KonceptDefinitions.forDocument(doc)
                .lookup(target)
                .flatMap(KonceptIdentity::idString);
    }

    /**
     * html5 / CSS-PDF: inline identicon image (data URI) + label, linked to
     * the glossary anchor.
     */
    private String renderHtmlIdenticon(String target, String label, String idString) {
        String dataUri = IdenticonRenderer.dataUri(idString);
        // Self-contained inline styles — no dependency on koncept.css, which
        // consuming documents may not link. A soft rounded "chip" rendered with
        // display:inline (NOT inline-block) so its vertical padding extends the
        // tint visually but never changes the line box height — lines holding a
        // koncept stay the same height as the rest of the paragraph. The chip
        // holds the identicon (0.9em, balanced against small caps) and a
        // small-caps IKE-blue label. white-space:nowrap + box-decoration-break
        // keep it a single intact pill.
        return """
            <a href="#koncept-%s" class="koncept-ref koncept-identicon-ref" title="%s" \
            style="text-decoration:none;white-space:nowrap;">\
            <span class="koncept-chip" style="display:inline;background:#e9eff6;\
            border-radius:0.5em;padding:0.12em 0.45em;\
            -webkit-box-decoration-break:clone;box-decoration-break:clone;">\
            <img class="koncept-identicon" src="%s" alt="%s identicon" \
            style="height:0.9em;width:0.9em;vertical-align:-0.12em;border-radius:2px;\
            image-rendering:pixelated;margin-right:0.3em;"/>\
            <span class="koncept-label" style="color:#2a5a8a;font-variant:small-caps;\
            letter-spacing:0.02em;">%s</span></span></a>\
            """.formatted(
                escapeXml(target), escapeXml(label), dataUri,
                escapeXml(label), escapeXml(label)).strip();
    }

    /**
     * DocBook5 &rarr; FO: inline identicon image referencing a generated PNG
     * file (resolved by FOP/XEP), with the label as alt text, linked to the
     * glossary entry.
     */
    private String renderDocbookIdenticon(String target, String label, String idString) {
        String uri = new File(IdenticonRenderer.pngFile(idString)).toURI().toString();
        return "<link linkend=\"koncept-" + escapeXml(target) + "\">"
                + "<inlinemediaobject>"
                + "<imageobject><imagedata fileref=\"" + escapeXml(uri) + "\""
                + " format=\"PNG\" contentwidth=\"12pt\" contentdepth=\"12pt\"/></imageobject>"
                + "<textobject><phrase>" + escapeXml(label) + "</phrase></textobject>"
                + "</inlinemediaobject></link>";
    }

    /** DocBook5 fallback when no identicon is available. */
    private String renderDocbookBadge(String target, String label) {
        return "<link linkend=\"koncept-" + escapeXml(target) + "\">"
                + "<phrase role=\"koncept\">K[" + escapeXml(label) + "]</phrase>"
                + "</link>";
    }

    /**
     * Prawn PDF: build a native inline image node referencing the generated
     * PNG file (absolute path; resolves under {@code SafeMode.UNSAFE}), linked
     * to the glossary anchor.
     */
    private PhraseNode createIdenticonImageNode(StructuralNode parent, String target,
                                               String label, String idString) {
        String absPath = IdenticonRenderer.pngFile(idString);
        Map<String, Object> attrs = new HashMap<>();
        attrs.put("alt", label);
        attrs.put("width", "18");
        attrs.put("link", "#koncept-" + target);
        Map<Object, Object> options = new HashMap<>();
        options.put("type", ":image");
        options.put("target", absPath);
        return createPhraseNode(parent, "image", List.<String>of(), attrs, options);
    }

    private String escapeXml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    /**
     * Resolve the display label for this koncept reference.
     * Priority: explicit bracket content > camelCase split of target.
     */
    private String resolveLabel(String target, Map<String, Object> attributes) {
        Object explicit = attributes.get("1");
        if (explicit != null && !explicit.toString().isBlank()) {
            return explicit.toString().strip();
        }
        return splitCamelCase(target);
    }

    /**
     * Split a CamelCase identifier into space-separated words.
     * "HeartFailure" → "Heart Failure"
     * "AcuteMyocardialInfarction" → "Acute Myocardial Infarction"
     */
    static String splitCamelCase(String s) {
        return s.replaceAll("([a-z])([A-Z])", "$1 $2")
                .replaceAll("([A-Z]+)([A-Z][a-z])", "$1 $2");
    }

    /**
     * Get or lazily create the document-scoped koncept registry.
     */
    static synchronized Map<String, KonceptEntry> getOrCreateRegistry(Document doc) {
        return REGISTRIES.computeIfAbsent(doc, d -> new ConcurrentHashMap<>());
    }

    /**
     * Retrieve the registry for a given document, or null if none exists.
     */
    static synchronized Map<String, KonceptEntry> getRegistry(Document doc) {
        return REGISTRIES.get(doc);
    }

    /**
     * Remove and return the registry for a given document.
     * Called by the postprocessor after consuming the registry to prevent
     * stale entries accumulating across conversions.
     */
    static synchronized Map<String, KonceptEntry> removeRegistry(Document doc) {
        return REGISTRIES.remove(doc);
    }

}
