package network.ike.docs.koncept;

import org.asciidoctor.ast.Document;
import org.asciidoctor.ast.PhraseNode;
import org.asciidoctor.ast.StructuralNode;
import org.asciidoctor.extension.InlineMacroProcessor;
import org.asciidoctor.extension.Name;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import network.ike.docs.konceptcore.KonceptKind;
import network.ike.docs.konceptcore.StampSigilGeometry;

import java.io.File;
import java.util.Map;
import java.util.Optional;
import java.util.WeakHashMap;
import java.util.concurrent.ConcurrentHashMap;

/**
 * AsciidoctorJ inline macro processor that handles {@code k:ConceptName[]}
 * syntax in AsciiDoc documents.
 * <p>
 * Usage in AsciiDoc:
 * <pre>
 * The patient presented with k:HeartFailure[] and k:AorticStenosis[].
 * A label override: k:HeartFailure[Congestive Heart Failure].
 * </pre>
 * <p>
 * Each reference renders as the concept's Komet identicon — a LifeHash image
 * byte-identical to what Komet draws — linked to the koncept's glossary
 * entry, with the form chosen per backend:
 * <ul>
 *   <li>{@code html5} / CSS-PDF (Prince, AH, WeasyPrint): an inline
 *       {@code <img>} with a base64 {@code data:} URI.</li>
 *   <li>{@code docbook5} &rarr; FO (FOP/XEP): an {@code <inlinemediaobject>}
 *       referencing a generated PNG file.</li>
 *   <li>{@code pdf} (Prawn): a native inline image node referencing the PNG.</li>
 * </ul>
 * When no identicon can be computed — the koncept has no resolvable PublicId,
 * or {@code :koncept-identicon:} is {@code false} — each backend falls back to
 * a text badge. The glossary is auto-generated by {@link KonceptGlossaryProcessor}.
 * <p>
 * All referenced koncepts are collected in a document-scoped registry
 * for deduplication and glossary generation.
 */
@Name("k")
public class KonceptInlineMacro extends InlineMacroProcessor {

    /** Creates a new inline macro processor instance. */
    public KonceptInlineMacro() {
    }

    private static final Logger LOG = LoggerFactory.getLogger(KonceptInlineMacro.class);

    /**
     * Static registry keyed by Document identity. Uses WeakHashMap so entries
     * are garbage-collected when the Document is no longer referenced.
     * AsciidoctorJ 3.0 does not preserve Java objects in document attributes,
     * so a static map is used for inter-extension communication.
     */
    private static final Map<Document, Map<String, KonceptEntry>> REGISTRIES =
            new WeakHashMap<>();

    @Override
    public PhraseNode process(StructuralNode parent, String target, Map<String, Object> attributes) {
        Document doc = parent.getDocument();

        // Positional attribute 1 is the bracket content: k:Target[label]. Resolve a name key OR a
        // typed id (k:sctid=/uuid=/id=/nid=) through the shared resolver, so the two forms render
        // identically here and inside a koncept-tree (ike-issues#837).
        Object bracket = attributes.get("1");
        String bracketLabel = bracket != null ? bracket.toString() : null;
        KonceptResolver.Resolved resolved = KonceptResolver.resolveTarget(doc, target, bracketLabel);
        String label = resolved.label();
        KonceptKind kind = resolved.kind();
        Optional<String> idString = resolved.idString();

        // Glossary anchor + registry key is the resolved concept identifier, so a name-key and a
        // typed-id reference to the same concept share one glossary entry. An uncurated reference
        // keys on its bare value; an uncurated TYPED id has no glossary entry, so it is not
        // registered (registering "sctid=…" would mint a bogus "missing definition" entry).
        String linkTarget = resolved.anchor() != null
                ? resolved.anchor() : KonceptResolver.bareValue(target);
        if (resolved.anchor() != null || !KonceptResolver.isTyped(target)) {
            KonceptEntry entry = getOrCreateRegistry(doc)
                    .computeIfAbsent(linkTarget, KonceptEntry::new);
            entry.incrementRefCount();
            LOG.debug("Koncept reference: {} → {} (total refs: {})",
                    target, linkTarget, entry.getRefCount());
        }

        // The rendered #koncept-… anchor is slugged: a curated identifier is already safe (no-op),
        // but an uncurated typed value (a comma in a multi-UUID id, a stray bracket) would otherwise
        // break the link attribute of the re-parsed Prawn image macro (the #836 class of bug).
        String renderLink = KonceptResolver.anchorSlug(linkTarget);
        String backend = doc.getAttribute("backend", "html5").toString();

        // A STAMP badge is provenance-shaped, not name-shaped: the pentagon sigil precedes the
        // STAMP's own identicon (the sigil is never bare — the identicon tells one STAMP from
        // another at a glance), and the compact provenance text stands in place of a name. Decided
        // BEFORE the generic dispatch so a stamp never renders as a small-caps name-pill.
        if (kind.isStamp()) {
            if (idString.isPresent()) {
                if ("pdf".equals(backend)) {
                    return createIdenticonChipNode(parent, renderLink, label, idString.get(), kind);
                }
                String rendered = ("docbook5".equals(backend) || "docbook".equals(backend))
                        ? renderDocbookIdenticon(renderLink, label, idString.get(), kind)
                        : renderHtmlStampChip(renderLink, label, idString.get());
                return createPhraseNode(parent, "quoted", rendered, Map.of("subs", ":none"));
            }
            return createPhraseNode(parent, "quoted", renderStamp(backend, renderLink, label),
                    Map.of("subs", ":none"));
        }

        // Prawn PDF: a passthrough <img> is not rendered by the Prawn converter, so return
        // re-processable AsciiDoc — a native inline image macro (the identicon) followed by the
        // visible name (ike-issues#836). Fall through to the text badge below when no identicon.
        if ("pdf".equals(backend) && idString.isPresent()) {
            return createIdenticonChipNode(parent, renderLink, label, idString.get(), kind);
        }

        String rendered;
        if ("docbook5".equals(backend) || "docbook".equals(backend)) {
            rendered = idString.isPresent()
                    ? renderDocbookIdenticon(renderLink, label, idString.get(), kind)
                    : renderDocbookBadge(renderLink, label);
        } else if ("pdf".equals(backend)) {
            // Prawn PDF without an identicon: only basic HTML is supported.
            rendered = "<strong><font color=\"#2a5a8a\">K</font></strong>"
                    + "<code>" + escapeXml(label) + "</code>";
        } else {
            // html5 and CSS-based PDF backends (Prince, AH, WeasyPrint).
            rendered = idString.isPresent()
                    ? renderHtmlIdenticon(renderLink, label, idString.get(), kind)
                    : KonceptSvgRenderer.render(renderLink, label, kind);
        }

        // Return as inline passthrough (no further substitution)
        return createPhraseNode(parent, "quoted", rendered,
                Map.of("subs", ":none"));
    }

    /**
     * html5 / CSS-PDF: inline identicon image (data URI) + label, linked to
     * the glossary anchor.
     */
    private String renderHtmlIdenticon(String target, String label, String idString, KonceptKind kind) {
        String dataUri = IdenticonRenderer.dataUri(idString);
        // Honest kind sigil (ike-issues#638): a Koncept stays bare; every other letter kind prepends
        // its coloured glyph (colour inline, from the kind, for cross-medium parity). Self-contained
        // inline styles — no dependency on koncept.css, which consuming documents may not link.
        String sigil = kind.hasLetterGlyph()
                ? "<span class=\"koncept-sigil koncept-sigil-%s\" "
                        .formatted(kind.name().toLowerCase(java.util.Locale.ROOT))
                        + "style=\"color:%s;font-weight:bold;margin-right:0.25em;\">%s</span>"
                        .formatted(kind.colorHex(), escapeXml(kind.glyph()))
                : "";
        // A soft rounded "chip" rendered with display:inline (NOT inline-block) so its vertical
        // padding extends the tint visually but never changes the line box height. The chip holds the
        // identicon (0.9em, balanced against small caps) and a small-caps IKE-blue label.
        return """
            <a href="#koncept-%s" class="koncept-ref koncept-identicon-ref" title="%s" \
            style="text-decoration:none;white-space:nowrap;">\
            <span class="koncept-chip" style="display:inline;background:#e9eff6;\
            border-radius:0.5em;padding:0.12em 0.45em;\
            -webkit-box-decoration-break:clone;box-decoration-break:clone;">\
            %s<img class="koncept-identicon" src="%s" alt="%s identicon" \
            style="height:0.9em;width:0.9em;vertical-align:-0.12em;border-radius:2px;\
            image-rendering:pixelated;margin-right:0.3em;"/>\
            <span class="koncept-label" style="color:#2a5a8a;font-variant:small-caps;\
            letter-spacing:0.02em;">%s</span></span></a>\
            """.formatted(
                escapeXml(target), escapeXml(label), sigil, dataUri,
                escapeXml(label), escapeXml(label)).strip();
    }

    /**
     * DocBook5 &rarr; FO: inline identicon image referencing a generated PNG
     * file (resolved by FOP/XEP), with the label as alt text, linked to the
     * glossary entry.
     */
    private String renderDocbookIdenticon(String target, String label, String idString, KonceptKind kind) {
        String uri = new File(IdenticonRenderer.pngFile(idString)).toURI().toString();
        // Honest kind glyph (ike-issues#638): a non-concept kind keeps its mark as text before the
        // identicon so it is not silently dropped in FO — the letter for letter kinds, ⬠ for a
        // stamp. The drawn pentagon is HTML-only; FO/Prawn carry the glyph (the data channel), not
        // necessarily its colour.
        String glyphPrefix = kind.isStamp()
                ? "<phrase role=\"koncept-sigil\">⬠ </phrase>"
                : kind.hasLetterGlyph()
                        ? "<phrase role=\"koncept-sigil\">" + escapeXml(kind.glyph()) + " </phrase>"
                        : "";
        // The visible name follows the identicon, inside the link, on EVERY backend (ike-issues#836):
        // the textobject phrase is only the image's fallback (shown if the PNG cannot render), so
        // without this the concept reads as a bare identicon in FO/print.
        return "<link linkend=\"koncept-" + escapeXml(target) + "\">"
                + glyphPrefix
                + "<inlinemediaobject>"
                + "<imageobject><imagedata fileref=\"" + escapeXml(uri) + "\""
                + " format=\"PNG\" contentwidth=\"12pt\" contentdepth=\"12pt\"/></imageobject>"
                + "<textobject><phrase>" + escapeXml(label) + "</phrase></textobject>"
                + "</inlinemediaobject>&#160;<phrase role=\"koncept-label\">" + escapeXml(label)
                + "</phrase></link>";
    }

    /**
     * html5 / CSS-PDF: the identicon-bearing STAMP chip — the pentagon sigil, then the STAMP's own
     * identicon (the sigil always precedes an identicon, never bare; the identicon tells one STAMP
     * from another at a glance), then the compact provenance text ({@code status · date-time ·
     * author}) in place of a name — on the gray provenance chip, linked to the glossary anchor.
     */
    private String renderHtmlStampChip(String target, String label, String idString) {
        String dataUri = IdenticonRenderer.dataUri(idString);
        String pentagon = KonceptSvgRenderer.pentagonSvg("", 22, 22,
                "height:0.95em;width:0.95em;vertical-align:-0.12em;margin-right:0.25em;");
        return """
            <a href="#koncept-%s" class="koncept-ref stamp-sigil" title="%s" \
            style="text-decoration:none;white-space:nowrap;">\
            <span class="koncept-chip koncept-stamp-chip" style="display:inline;background:#ecebe8;\
            border-radius:0.5em;padding:0.12em 0.45em;\
            -webkit-box-decoration-break:clone;box-decoration-break:clone;">\
            %s<img class="koncept-identicon" src="%s" alt="%s identicon" \
            style="height:0.9em;width:0.9em;vertical-align:-0.12em;border-radius:2px;\
            image-rendering:pixelated;margin-right:0.3em;"/>\
            <span class="koncept-label" style="color:#5a5750;">%s</span></span></a>\
            """.formatted(
                escapeXml(target), escapeXml(label), pentagon, dataUri,
                escapeXml(label), escapeXml(label)).strip();
    }

    /**
     * A stamp's per-backend rendering when no identicon can be computed: on html5 (and CSS-PDF) the
     * locked gray pentagon plus the compact provenance text; on docbook5/FO a gray phrase; on Prawn
     * gray inline text. With a computable identity a stamp renders identicon-bearing instead — see
     * {@link #renderHtmlStampChip(String, String, String)} and the stamp-aware identicon paths.
     *
     * @param backend the asciidoctor backend
     * @param target  the koncept identifier (anchor)
     * @param label   the compact stamp provenance text
     * @return the per-backend inline markup for the stamp
     */
    private String renderStamp(String backend, String target, String label) {
        if ("docbook5".equals(backend) || "docbook".equals(backend)) {
            return "<link linkend=\"koncept-" + escapeXml(target) + "\">"
                    + "<phrase role=\"koncept-stamp\">⬠ " + escapeXml(label) + "</phrase></link>";
        }
        if ("pdf".equals(backend)) {
            return "<font color=\"" + escapeXml(StampSigilGeometry.COLOR) + "\">⬠</font> "
                    + "<code>" + escapeXml(label) + "</code>";
        }
        return KonceptSvgRenderer.renderStampSigil(target, label);
    }

    /** DocBook5 fallback when no identicon is available. */
    private String renderDocbookBadge(String target, String label) {
        return "<link linkend=\"koncept-" + escapeXml(target) + "\">"
                + "<phrase role=\"koncept\">K[" + escapeXml(label) + "]</phrase>"
                + "</link>";
    }

    /**
     * Prawn PDF: the identicon chip as re-processable AsciiDoc — a native inline {@code image:}
     * macro (which Prawn renders from the generated PNG; a passthrough {@code <img>} would not
     * render) followed by the visible concept name (ike-issues#836). The image carries the
     * glossary link; a non-concept kind's letter glyph precedes it. Returned as a {@code quoted}
     * node whose {@code specialcharacters,macros} substitutions render the image and escape the
     * label without letting a stray {@code *} or {@code _} in a name turn into formatting.
     */
    private PhraseNode createIdenticonChipNode(StructuralNode parent, String target,
                                               String label, String idString, KonceptKind kind) {
        String absPath = IdenticonRenderer.pngFile(idString);
        String glyph = kind.isStamp() ? "⬠ " : (kind.hasLetterGlyph() ? kind.glyph() + " " : "");
        // Content is RAW, not pre-escaped: the specialcharacters substitution escapes the glyph and
        // label, and the macros substitution renders the inline image — pre-escaping here would
        // double-escape. A literal non-breaking space (U+00A0, not an &#160; entity, which the
        // substitution would mangle) keeps the identicon and name on one line.
        String content = glyph + "image:" + absPath + "[" + attrValue(label)
                + ",18,18,link=#koncept-" + target + "]\u00A0" + label;
        return createPhraseNode(parent, "quoted", content,
                Map.of("subs", "specialcharacters,macros"));
    }

    /**
     * Renders a value safe to embed as an inline-macro attribute: quoted so a comma cannot split
     * the attribute list, and with {@code ]} backslash-escaped so it cannot prematurely close the
     * macro — Asciidoctor's macro-boundary regex terminates the attrlist at the first unescaped
     * {@code ]} <em>before</em> quotes are parsed, so quoting alone does not protect it. (SNOMED CT
     * carries bracketed descriptions like {@code [D]Chest pain}.)
     */
    private static String attrValue(String value) {
        return "\"" + value.replace("\"", "\\\"").replace("]", "\\]") + "\"";
    }

    private String escapeXml(String s) {
        return escapeXmlStatic(s);
    }

    private static String escapeXmlStatic(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    /**
     * A specimen chip for a letter-glyph component kind: the kind's sigil and a label in
     * the same soft chip the identicon badges use, but unlinked and with no identicon —
     * for prose that shows what a badge of this kind looks like (a "How to Read This
     * Guide" front matter) without claiming a reference to a curated component. Stamps
     * render via {@link KonceptSvgRenderer#renderStampSpecimen(String)} instead.
     *
     * @param kind  the component kind whose sigil leads the chip
     * @param label the specimen's display text
     * @return the chip HTML, unlinked
     */
    static String renderSpecimenChip(KonceptKind kind, String label) {
        String sigil = kind.hasLetterGlyph()
                ? "<span class=\"koncept-sigil koncept-sigil-%s\" "
                        .formatted(kind.name().toLowerCase(java.util.Locale.ROOT))
                        + "style=\"color:%s;font-weight:bold;margin-right:0.25em;\">%s</span>"
                        .formatted(kind.colorHex(), escapeXmlStatic(kind.glyph()))
                : "";
        return """
            <span class="koncept-chip koncept-specimen" style="display:inline;background:#e9eff6;\
            border-radius:0.5em;padding:0.12em 0.45em;\
            -webkit-box-decoration-break:clone;box-decoration-break:clone;white-space:nowrap;">\
            %s<span class="koncept-label" style="color:#2a5a8a;font-variant:small-caps;\
            letter-spacing:0.02em;">%s</span></span>\
            """.formatted(sigil, escapeXmlStatic(label)).strip();
    }

    /**
     * Split a CamelCase identifier into space-separated words.
     * "HeartFailure" → "Heart Failure"
     * "AcuteMyocardialInfarction" → "Acute Myocardial Infarction"
     */
    static String splitCamelCase(String s) {
        return s.replaceAll("([a-z])([A-Z])", "$1 $2")
                .replaceAll("([A-Z]+)([A-Z][a-z])", "$1 $2");
    }

    /**
     * Get or lazily create the document-scoped koncept registry.
     */
    static synchronized Map<String, KonceptEntry> getOrCreateRegistry(Document doc) {
        return REGISTRIES.computeIfAbsent(doc, d -> new ConcurrentHashMap<>());
    }

    /**
     * Retrieve the registry for a given document, or null if none exists.
     */
    static synchronized Map<String, KonceptEntry> getRegistry(Document doc) {
        return REGISTRIES.get(doc);
    }

    /**
     * Remove and return the registry for a given document.
     * Called by the postprocessor after consuming the registry to prevent
     * stale entries accumulating across conversions.
     */
    static synchronized Map<String, KonceptEntry> removeRegistry(Document doc) {
        return REGISTRIES.remove(doc);
    }

}
