/*
 * Copyright © 2026 Knowledge Graphlet / IKE Network
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package network.ike.docs.konceptcore;

/**
 * The Koncept glyph <em>inventory</em> (ike-issues#953): every symbol codepoint an IKE renderer
 * draws, which the bundled <em>IKE Koncept Glyphs</em> face must therefore cover. The face exists
 * because none of the text families the apps bundle contain these codepoints, so without it every
 * status cluster and operator was drawn by ambient OS font fallback — and fallback answers differ
 * per requested base font, per machine, and per platform (the #953 flip: Apple SD Gothic Neo
 * ships the {@code U+22CE}/{@code U+22CF} pair with swapped glyphs, so the multi-parent fork
 * rendered upside-down in surfaces whose fallback landed there, while the drag glyph and the
 * documentation rendered it correctly).
 *
 * <p>The face is a merged subset of pinned Noto releases (SIL OFL 1.1; licence and provenance in
 * {@code IKEKonceptGlyphs-OFL.txt} beside the TTF), regenerated by
 * {@code koncept-core/src/build/regen-koncept-glyphs.py} — whose own codepoint list mirrors this
 * one. {@code KonceptGlyphsTest} fails the build if the checked-in face ever lags this
 * inventory, so adding a codepoint here forces the regeneration.
 *
 * <p>The glyph <em>identities</em> stay where they are owned — {@link KonceptStatus} for the
 * copula cluster, renderer code for its operators. This class only declares what the face must
 * cover; {@link KonceptAppearance#glyphFamilyName()} names the family renderers request.
 */
public final class KonceptGlyphs {

    /**
     * The inventoried codepoints. Layout: space and no-break space (cluster and chip-line
     * separators). Logical-status cluster: {@code ≡ ⊑ ⊤ ⋎} and the fork's sibling {@code ⋏}.
     * Operators: {@code ∃ ⊓ ⊔ → ⇒ ➞ ≤ ≥ π σ ⒡} and the {@code ⬠} STAMP pentagon stand-in for
     * text channels. Chrome: {@code … · • − ∞ ▲ ▼ ▶ ◀ ▸ ▾ ◌ ● ☰ ⚠ ✓ ✕ ⌘ ⬛ ⬜}.
     */
    private static final int[] INVENTORY = {
            0x0020, 0x00A0,
            0x2261, 0x2291, 0x22A4, 0x22CE, 0x22CF,
            0x2203, 0x2293, 0x2294, 0x2192, 0x21D2, 0x279E, 0x2264, 0x2265,
            0x03C0, 0x03C3, 0x24A1, 0x2B20,
            0x2026, 0x00B7, 0x2022, 0x2212, 0x221E,
            0x25B2, 0x25BC, 0x25B6, 0x25C0, 0x25B8, 0x25BE, 0x25CC, 0x25CF,
            0x2630, 0x26A0, 0x2713, 0x2715, 0x2318, 0x2B1B, 0x2B1C,
    };

    private KonceptGlyphs() {
    }

    /**
     * The inventoried codepoints the bundled face must cover, in inventory order.
     *
     * @return a fresh array of Unicode codepoints (never {@code null})
     */
    public static int[] codePoints() {
        return INVENTORY.clone();
    }
}
